# K8S-CKAD-training
:toc:
:toc-placement!:

CKAD training resources

toc::[]

## Tips

### Change the default editor
By default, the editor used to modify k8s resources is Vim. As we are not all familiar with this editr, it is possible to use nano instead :
----
export KUBE_EDITOR="nano"
----

### Use aliases
It is really time consuming to write a full kubectl command, it can be usefull to define aliases :
----
export ns=default
alias k='kubectl -n $ns' # This helps when namespace in question doesn't have a friendly name 
----

### Output formating
The default output format for all kubectl commands is the human-readable plain-text format.
The -o flag allows us to output the details in several different formats.
Here are some of the commonly used formats:

* `-o jsonOutput` a JSON formatted API object.
* `-o namePrint` only the resource name and nothing else.
* `-o wideOutput` in the plain-text format with any additional information.
* `-o yamlOutput` a YAML formatted API object.

### generate a yaml template
Whatever the kind of k8s resource, it is possible to generate simply a yaml template into a file :
----
k run my-pod --image=nginx --restart=Never --dry-run -o yaml > my-pod.yaml
----

Then, this file can be completed and used to create the resource :
----
k create -f my-pod.yaml
----

## Configuration

### Pods
**Generate yaml**
----
k run my-pod --image=nginx --restart=Never --dry-run -o yaml
----

### Jobs
**Generate yaml**
----
k run my-job --image=nginx --restart=OnFailure --dry-run -o yaml
----

### Cronjobs
**Generate yaml**
----
k run my-cronjob --image=nginx --restart=OnFailure --schedule="*/15 * * * *" --dry-run -o yaml
----

### Deployments
**Generate yaml**
----
k run my-cronjob --image=nginx --dry-run -o yaml
k create deploy my-deploy --image=nginx -o yaml --dry-run
----

**Update the replicas**
----
k scale deploy my-deploy --replicas=3
----

### Service
**Generate yaml**
----
k expose pod nginx --port=8080 --name nginx-service --dry-run -o yaml
k create service clusterip nginx --tcp=8080:8080 --dry-run -o yaml
----


### Namespaces
**Generate yaml**
----
k create namespace my-namespace --dry-run -o yaml
----

**Specify a namespace**
----
k get pods -n my-namespace
k get pods --namespace my-namespace
k get pods --all-namespaces
----

### Configmaps
**Generate yaml**
----
k create cm my-cm --from-literal MY_ENV=my_value -o yaml --dry-run

echo "MY_ENV=my_value" > envs.txt
k create cm my-cm --from-file envs.txt -o yaml --dry-run
----

**Reference a cm to a pod**
[source,yaml]
----
envFrom:
  - configMapRef:
      name: my-cm

env:
  - name: MY_ENV
    valueFrom:
      configMapKeyRef:
        name: my-cm
        key: MY_ENV

----

### Secrets
**Generate yaml**
----
k create secret generic my-secret --from-literal MY_ENV=my_value -o yaml --dry-run

echo "MY_ENV=my_value" > envs.txt
k create secret generic my-secret --from-file envs.txt -o yaml --dry-run
----

**Reference a cm to a pod**
[source,yaml]
----
envFrom:
  - secretRef:
      name: my-secret

env:
  - name: MY_ENV
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: MY_ENV

----

**Encode & decode secrets**
----
# encode
echo -n 'my_value' | base64

# decode
echo -n 'bXlfdmFsdWU=' | base64 --decode
----

### Security Contexts

**Update security context**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  # At pod level
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx
      image: nginx
      # Or at container lever
      securityContext:
        runAsUser: 2000
        capabilities:
          add: ["MAC_ADMIN"]
----

### Service Accounts

**Generate yaml**
----
k create sa my-sa --dry-run -o yaml
----

**Reference asevice account**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  # Change default service account
  serviceAccount: my-sa
  # Do not mount automatically service account token
  automountServiceAccountToken: false
  containers:
    - name: nginx
      image: nginx
----

**Resource Requirements**

**Specify resource requirements**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
----

### Taints & Tolerations

**Taint a node**
----
k taint nodes my-node key=value:taint-effect
----

taint-effect can be :

* `NoSchedule`: Pod with wrong toleration won't be schedule
* `PreferNoSchedule`: Pod with wrong toleration won't be schedule, if possible, no warranty
* `NoExecute`: Pod with wrong toleration won't be schedule and existing pod with wrong toleration will be killed

**Apply a toleration to a pod**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "taint-effect"
----

### Node Selectors

**Label a node**
----
k label nodes my-node key=value
----

**Specify a node selector to a pod**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    key: value
----

### Node affinity

**Specify an affinity to a pod**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      # preferredDuringSchedulingIgnoredDuringExecution
      # requiredDuringSchedulingRequiredDuringExecution
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key
            operator: In|NotIn|Exists
            values:
            - value
----

## Observability

### Readiness & Liveness

**Specify readiness**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      # Is the container ready ?
      readinessProbe:
        # tcpSocket:
        # exec:
        #   command:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
----

**Specify liveness**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      # Is the container still alive ?
      livenessProbe:
        # tcpSocket:
        # exec:
        #   command:
        httpGet:
          path: /api/alive
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
----

### Logging

**View pod logs**
----
k logs -f my-pod
----

**View pod logs for a specific container**
----
k logs -f my-pod my-container
----

### Monitor & debug

**Setup Metric Server**
----
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml
----

**Monitor resources**
----
kubectl top node
kubectl top pod
----

## Pod design

### Labels, Selector & Annotations

**Labels definition**
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app-label
    function: my-function-label
spec:
  containers:
    - name: my-app
      image: my-app
----

**Get filtered by label**
----
k get pods --selector key=value
----

**Selector definition**
[source,yaml]
----
apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: my-app-label
    function: my-function-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-label
      function: my-function-label
  template:
    [...]
----

[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app-label
    function: my-function-label
spec:
  selector:
    matchLabels:
      app: my-app-label
      function: my-function-label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
----

**Annotations definition**
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    buildVersions: 1.34
spec:
  selector:
    matchLabels:
      app: my-app-label
      function: my-function-label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
----

### Rolling Updates & Rollbacks in Deployments

**Create deployment**
----
k create -f deploy-def.yaml
----

**Get deployment**
----
k get deploy
----

**Update a deployment**
----
k apply -f deploy-def.yaml
k set image deploy/my-deploy container=newImage
k edit deploy my-deploy [--record]
----

**Get deployment status**
----
k rollout status deploy/my-deploy
k rollout history deploy/my-deploy [--version=version]
----

**Rollback a deployment**
----
k rollout undo deploy/my-deploy
----

### Jobs & Cronjobs

**Job definition**
[source,yaml]
----
apiVersion: v1
kind: Job
metadata:
  name: my-job
spec:
  # Number of pods to create
  completions: 3
  # Number of pods created in parallel
  parallelism: 3
  template:
    [Pod definition]
----

**CronJob definition**
[source,yaml]
----
apiVersion: v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  # Cron definition
  schedule: "*/1 * * * *"
  jobTemplate:
    [Job definition]
----
